//
//  Countries.swift
//  Traver
//
//  Created by Natalia Nikitina on 11/22/16.
//  Copyright © 2016 Natalia Nikitina. All rights reserved.
//

import Foundation

class Countries {
    
    static let codesAndCountries = ["AE": "United Arab Emirates",
                                    "AF": "Afghanistan",
                                    "AL": "Albania",
                                    "AM": "Armenia",
                                    "AO": "Angola",
                                    "AR": "Argentina",
                                    "AT": "Austria",
                                    "AU": "Australia",
                                    "AZ": "Azerbaijan",
                                    "BA": "Bosnia and Herzegovina",
                                    "BD": "Bangladesh",
                                    "BE": "Belgium",
                                    "BF": "Burkina Faso",
                                    "BG": "Bulgaria",
                                    "BI": "Burundi",
                                    "BJ": "Benin",
                                    "BN": "Brunei Darussalam",
                                    "BO": "Bolivia",
                                    "BR": "Brazil",
                                    "BS": "Bahamas",
                                    "BT": "Bhutan",
                                    "BW": "Botswana",
                                    "BY": "Belarus",
                                    "BZ": "Belize",
                                    "CA": "Canada",
                                    "CD": "Democratic Republic of Congo",
                                    "CF": "Central African Republic",
                                    "CG": "Republic of Congo",
                                    "CH": "Switzerland",
                                    "CI": "Côte d'Ivoire",
                                    "CL": "Chile",
                                    "CM": "Cameroon",
                                    "CN": "China",
                                    "CO": "Colombia",
                                    "CR": "Costa Rica",
                                    "CU": "Cuba",
                                    "CY": "Cyprus",
                                    "CZ": "Czech Republic",
                                    "DE": "Germany",
                                    "DJ": "Djibouti",
                                    "DK": "Denmark",
                                    "DO": "Dominican Republic",
                                    "DZ": "Algeria",
                                    "EC": "Ecuador",
                                    "EE": "Estonia",
                                    "EG": "Egypt",
                                    "EH": "Western Sahara",
                                    "ER": "Eritrea",
                                    "ES": "Spain",
                                    "ET": "Ethiopia",
                                    "FK": "Falkland Islands",
                                    "FI": "Finland",
                                    "FJ": "Fiji",
                                    "FR": "France",
                                    "GA": "Gabon",
                                    "GB": "United Kingdom",
                                    "GE": "Georgia",
                                    "GF": "French Guiana",
                                    "GH": "Ghana",
                                    "GL": "Greenland",
                                    "GM": "Gambia",
                                    "GN": "Guinea",
                                    "GQ": "Equatorial Guinea",
                                    "GR": "Greece",
                                    "GT": "Guatemala",
                                    "GW": "Guinea-Bissau",
                                    "GY": "Guyana",
                                    "HN": "Honduras",
                                    "HR": "Croatia",
                                    "HT": "Haiti",
                                    "HU": "Hungary",
                                    "ID": "Indonesia",
                                    "IE": "Ireland",
                                    "IL": "Israel",
                                    "IN": "India",
                                    "IQ": "Iraq",
                                    "IR": "Iran",
                                    "IS": "Iceland",
                                    "IT": "Italy",
                                    "JM": "Jamaica",
                                    "JO": "Jordan",
                                    "JP": "Japan",
                                    "KE": "Kenya",
                                    "KG": "Kyrgyzstan",
                                    "KH": "Cambodia",
                                    "KP": "North Korea",
                                    "KR": "South Korea",
                                    "XK": "Kosovo",
                                    "KW": "Kuwait",
                                    "KZ": "Kazakhstan",
                                    "LA": "Lao People's Democratic Republic",
                                    "LB": "Lebanon",
                                    "LK": "Sri Lanka",
                                    "LR": "Liberia",
                                    "LS": "Lesotho",
                                    "LT": "Lithuania",
                                    "LU": "Luxembourg",
                                    "LV": "Latvia",
                                    "LY": "Libya",
                                    "MA": "Morocco",
                                    "MD": "Moldova",
                                    "ME": "Montenegro",
                                    "MG": "Madagascar",
                                    "MK": "Macedonia",
                                    "ML": "Mali",
                                    "MM": "Myanmar",
                                    "MN": "Mongolia",
                                    "MR": "Mauritania",
                                    "MW": "Malawi",
                                    "MX": "Mexico",
                                    "MY": "Malaysia",
                                    "MZ": "Mozambique",
                                    "NA": "Namibia",
                                    "NC": "New Caledonia",
                                    "NE": "Niger",
                                    "NG": "Nigeria",
                                    "NI": "Nicaragua",
                                    "NL": "Netherlands",
                                    "NO": "Norway",
                                    "NP": "Nepal",
                                    "NZ": "New Zealand",
                                    "OM": "Oman",
                                    "PA": "Panama",
                                    "PE": "Peru",
                                    "PG": "Papua New Guinea",
                                    "PH": "Philippines",
                                    "PL": "Poland",
                                    "PK": "Pakistan",
                                    "PR": "Puerto Rico",
                                    "PS": "Palestinian Territories",
                                    "PT": "Portugal",
                                    "PY": "Paraguay",
                                    "QA": "Qatar",
                                    "RO": "Romania",
                                    "RS": "Serbia",
                                    "RU": "Russia",
                                    "RW": "Rwanda",
                                    "SA": "Saudi Arabia",
                                    "SB": "Solomon Islands",
                                    "SD": "Sudan",
                                    "SE": "Sweden",
                                    "SI": "Slovenia",
                                    "SJ": "Svalbard and Jan Mayen",
                                    "SK": "Slovakia",
                                    "SL": "Sierra Leone",
                                    "SN": "Senegal",
                                    "SO": "Somalia",
                                    "SR": "Suriname",
                                    "SS": "South Sudan",
                                    "SV": "El Salvador",
                                    "SY": "Syria",
                                    "SZ": "Swaziland",
                                    "TD": "Chad",
                                    "TF": "French Southern and Antarctic Lands",
                                    "TG": "Togo",
                                    "TH": "Thailand",
                                    "TJ": "Tajikistan",
                                    "TL": "Timor-Leste",
                                    "TM": "Turkmenistan",
                                    "TN": "Tunisia",
                                    "TR": "Turkey",
                                    "TT": "Trinidad and Tobago",
                                    "TW": "Taiwan",
                                    "TZ": "Tanzania",
                                    "UA": "Ukraine",
                                    "UG": "Uganda",
                                    "US": "United States",
                                    "UY": "Uruguay",
                                    "UZ": "Uzbekistan",
                                    "VE": "Venezuela",
                                    "VN": "Vietnam",
                                    "VU": "Vanuatu",
                                    "YE": "Yemen",
                                    "ZA": "South Africa",
                                    "ZM": "Zambia",
                                    "ZW": "Zimbabwe"]

    static let codes = ["AE",
                        "AF",
                        "AL",
                        "AM",
                        "AO",
                        "AR",
                        "AT",
                        "AU",
                        "AZ",
                        "BA",
                        "BD",
                        "BE",
                        "BF",
                        "BG",
                        "BI",
                        "BJ",
                        "BN",
                        "BO",
                        "BR",
                        "BS",
                        "BT",
                        "BW",
                        "BY",
                        "BZ",
                        "CA",
                        "CD",
                        "CF",
                        "CG",
                        "CH",
                        "CI",
                        "CL",
                        "CM",
                        "CN",
                        "CO",
                        "CR",
                        "CU",
                        "CY",
                        "CZ",
                        "DE",
                        "DJ",
                        "DK",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "EH",
                        "ER",
                        "ES",
                        "ET",
                        "FK",
                        "FI",
                        "FJ",
                        "FR",
                        "GA",
                        "GB",
                        "GE",
                        "GF",
                        "GH",
                        "GL",
                        "GM",
                        "GN",
                        "GQ",
                        "GR",
                        "GT",
                        "GW",
                        "GY",
                        "HN",
                        "HR",
                        "HT",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IQ",
                        "IR",
                        "IS",
                        "IT",
                        "JM",
                        "JO",
                        "JP",
                        "KE",
                        "KG",
                        "KH",
                        "KP",
                        "KR",
                        "XK",
                        "KW",
                        "KZ",
                        "LA",
                        "LB",
                        "LK",
                        "LR",
                        "LS",
                        "LT",
                        "LU",
                        "LV",
                        "LY",
                        "MA",
                        "MD",
                        "ME",
                        "MG",
                        "MK",
                        "ML",
                        "MM",
                        "MN",
                        "MR",
                        "MW",
                        "MX",
                        "MY",
                        "MZ",
                        "NA",
                        "NC",
                        "NE",
                        "NG",
                        "NI",
                        "NL",
                        "NO",
                        "NP",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PG",
                        "PH",
                        "PL",
                        "PK",
                        "PR",
                        "PS",
                        "PT",
                        "PY",
                        "QA",
                        "RO",
                        "RS",
                        "RU",
                        "RW",
                        "SA",
                        "SB",
                        "SD",
                        "SE",
                        "SI",
                        "SJ",
                        "SK",
                        "SL",
                        "SN",
                        "SO",
                        "SR",
                        "SS",
                        "SV",
                        "SY",
                        "SZ",
                        "TD",
                        "TF",
                        "TG",
                        "TH",
                        "TJ",
                        "TL",
                        "TM",
                        "TN",
                        "TR",
                        "TT",
                        "TW",
                        "TZ",
                        "UA",
                        "UG",
                        "US",
                        "UY",
                        "UZ",
                        "VE",
                        "VN",
                        "VU",
                        "YE",
                        "ZA",
                        "ZM",
                        "ZW"]

    static let countries = ["United Arab Emirates",
                            "Afghanistan",
                            "Albania",
                            "Armenia",
                            "Angola",
                            "Argentina",
                            "Austria",
                            "Australia",
                            "Azerbaijan",
                            "Bosnia and Herzegovina",
                            "Bangladesh",
                            "Belgium",
                            "Burkina Faso",
                            "Bulgaria",
                            "Burundi",
                            "Benin",
                            "Brunei Darussalam",
                            "Bolivia",
                            "Brazil",
                            "Bahamas",
                            "Bhutan",
                            "Botswana",
                            "Belarus",
                            "Belize",
                            "Canada",
                            "Democratic Republic of Congo",
                            "Central African Republic",
                            "Republic of Congo",
                            "Switzerland",
                            "Côte d'Ivoire",
                            "Chile",
                            "Cameroon",
                            "China",
                            "Colombia",
                            "Costa Rica",
                            "Cuba",
                            "Cyprus",
                            "Czech Republic",
                            "Germany",
                            "Djibouti",
                            "Denmark",
                            "Dominican Republic",
                            "Algeria",
                            "Ecuador",
                            "Estonia",
                            "Egypt",
                            "Western Sahara",
                            "Eritrea",
                            "Spain",
                            "Ethiopia",
                            "Falkland Islands",
                            "Finland",
                            "Fiji",
                            "France",
                            "Gabon",
                            "United Kingdom",
                            "Georgia",
                            "French Guiana",
                            "Ghana",
                            "Greenland",
                            "Gambia",
                            "Guinea",
                            "Equatorial Guinea",
                            "Greece",
                            "Guatemala",
                            "Guinea-Bissau",
                            "Guyana",
                            "Honduras",
                            "Croatia",
                            "Haiti",
                            "Hungary",
                            "Indonesia",
                            "Ireland",
                            "Israel",
                            "India",
                            "Iraq",
                            "Iran",
                            "Iceland",
                            "Italy",
                            "Jamaica",
                            "Jordan",
                            "Japan",
                            "Kenya",
                            "Kyrgyzstan",
                            "Cambodia",
                            "North Korea",
                            "South Korea",
                            "Kosovo",
                            "Kuwait",
                            "Kazakhstan",
                            "Lao People's Democratic Republic",
                            "Lebanon",
                            "Sri Lanka",
                            "Liberia",
                            "Lesotho",
                            "Lithuania",
                            "Luxembourg",
                            "Latvia",
                            "Libya",
                            "Morocco",
                            "Moldova",
                            "Montenegro",
                            "Madagascar",
                            "Macedonia",
                            "Mali",
                            "Myanmar",
                            "Mongolia",
                            "Mauritania",
                            "Malawi",
                            "Mexico",
                            "Malaysia",
                            "Mozambique",
                            "Namibia",
                            "New Caledonia",
                            "Niger",
                            "Nigeria",
                            "Nicaragua",
                            "Netherlands",
                            "Norway",
                            "Nepal",
                            "New Zealand",
                            "Oman",
                            "Panama",
                            "Peru",
                            "Papua New Guinea",
                            "Philippines",
                            "Poland",
                            "Pakistan",
                            "Puerto Rico",
                            "Palestinian Territories",
                            "Portugal",
                            "Paraguay",
                            "Qatar",
                            "Romania",
                            "Serbia",
                            "Russia",
                            "Rwanda",
                            "Saudi Arabia",
                            "Solomon Islands",
                            "Sudan",
                            "Sweden",
                            "Slovenia",
                            "Svalbard and Jan Mayen",
                            "Slovakia",
                            "Sierra Leone",
                            "Senegal",
                            "Somalia",
                            "Suriname",
                            "South Sudan",
                            "El Salvador",
                            "Syria",
                            "Swaziland",
                            "Chad",
                            "French Southern and Antarctic Lands",
                            "Togo",
                            "Thailand",
                            "Tajikistan",
                            "Timor-Leste",
                            "Turkmenistan",
                            "Tunisia",
                            "Turkey",
                            "Trinidad and Tobago",
                            "Taiwan",
                            "Tanzania",
                            "Ukraine",
                            "Uganda",
                            "United States",
                            "Uruguay",
                            "Uzbekistan",
                            "Venezuela",
                            "Vietnam",
                            "Vanuatu",
                            "Yemen",
                            "South Africa",
                            "Zambia",
                            "Zimbabwe"]
    
}
